Prepare csv files downloaded from PubChem database

In [ ]:
##import libraries
import pandas as pd
import numpy as np

In [ ]:
import pandas as pd

# File paths and index_col specifications
file_paths = [
    ('/Manuscrip_preparation/compounds/AID_1247343_datatable_all.csv', None),
    ('/Manuscrip_preparation/compounds/AID_624148_datatable_all.csv', None),
    ('/Manuscrip_preparation/compounds/AID_624172_datatable_all.csv', None),
    ('/Manuscrip_preparation/compounds/AID_743262_datatable_all.csv', None),
    ('/content/AID_1247343_datatable.csv', 0),
    ('/content/AID_1247344_datatable_all.csv', 0),
    ('/content/AID_1247346_datatable_all.csv', 0),
    ('/content/AID_1388614_datatable_all.csv', 0),
    ('/content/AID_1388618_datatable_all.csv', 0),
    ('/content/AID_1392277_datatable_all.csv', 0),
    ('/content/AID_1411355_datatable_all.csv', 0),
    ('/content/AID_1411991_datatable_all.csv', 0),
    ('/content/AID_1450908_datatable_all.csv', 0),
    ('/content/AID_1573521_datatable_all.csv', 0),
    ('/content/AID_1573523_datatable_all.csv', 0),
    ('/content/AID_1573525_datatable_all.csv', 0),
    ('/content/AID_1578075_datatable_all.csv', 0),
    ('/content/AID_1601241_datatable_all.csv', 0),
    ('/content/AID_309641_datatable_all.csv', 0),
    ('/content/AID_328850_datatable_all.csv', 0)
]

# Read the files and store in a list
data = [pd.read_csv(file_path, index_col=index_col) for file_path, index_col in file_paths]

# Drop the first 5 rows for each DataFrame
for df in data:
    df.drop(df.index[:5], inplace=True)

In [ ]:
data_one = pd.concat(data, axis=0) #merge all data
data_one[data_one['PUBCHEM_EXT_DATASOURCE_SMILES'].isna()] #remove all rows of column with NAN values

,PUBCHEM_RESULT_TAG,PUBCHEM_SID,PUBCHEM_CID,PUBCHEM_EXT_DATASOURCE_SMILES,PUBCHEM_ACTIVITY_OUTCOME,PUBCHEM_ACTIVITY_SCORE,PUBCHEM_ACTIVITY_URL,PUBCHEM_ASSAYDATA_COMMENT,PubChem Standard Value,Standard Type,...,Activity at 0.029 uM,Activity at 0.033 uM,Activity at 0.159 uM,Activity at 0.794 uM,Activity at 3.690 uM,Activity at 4.120 uM,Activity at 19.84 uM,Activity at 92.20 uM,Data Validity Comment,Activity Comment
6,2,160693094.0,NaN,NaN,Active,NaN,NaN,NaN,0.00038,IC50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
482,478,124899218.0,NaN,NaN,Inactive,0.0,http://assay.nih.gov/htsws/rest/display/glp1r-...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
483,479,124899219.0,NaN,NaN,Inactive,0.0,http://assay.nih.gov/htsws/rest/display/glp1r-...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45019,45015,29216072.0,NaN,NaN,Inactive,0.0,http://assay.nih.gov/htsws/rest/display/glp1r-...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45139,45135,50126343.0,NaN,NaN,Inactive,0.0,http://assay.nih.gov/htsws/rest/display/glp1r-...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
308372,308368,124894389.0,NaN,NaN,Inactive,0.0,http://assay.nih.gov/htsws/rest/display/glp1r-...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
333234,333230,99495786.0,NaN,NaN,Inactive,0.0,http://assay.nih.gov/htsws/rest/display/glp1r-...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
334307,334303,50109866.0,NaN,NaN,Inactive,0.0,http://assay.nih.gov/htsws/rest/display/glp1r-...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,160693094.0,NaN,NaN,Active,NaN,NaN,NaN,0.00038,IC50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,160693094.0,NaN,NaN,Active,NaN,NaN,NaN,0.357,IC50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,160693094.0,NaN,NaN,Active,NaN,NaN,NaN,6.2e-06,EC50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Outside typical range,NaN

In [ ]:
data_one['PUBCHEM_ACTIVITY_OUTCOME'].value_counts()

Inactive        374822
Inconclusive      2992
Active             350
Unspecified          5
Name: PUBCHEM_ACTIVITY_OUTCOME, dtype: int64

Extract PubChem CID, SMILES and Activity outcome from data

In [ ]:
data_2 = pd.concat([data_one['PUBCHEM_CID'], data_one['PUBCHEM_EXT_DATASOURCE_SMILES'], data_one['PUBCHEM_ACTIVITY_OUTCOME']], axis =1)
data_2

,PUBCHEM_CID,PUBCHEM_EXT_DATASOURCE_SMILES,PUBCHEM_ACTIVITY_OUTCOME
5,44290899.0,CC[C@H](C)[C@@H](C(=O)N[C@@H](C)C(=O)N[C@@H](C...,Active
6,NaN,NaN,Active
7,122189729.0,CC[C@H](C)[C@@H](C(=O)N[C@@H](C)C(=O)N[C@@H](C...,Active
8,122189730.0,CCCCCCCCCCCCCCCCCC(=O)N[C@H](CCC(=O)NCCCC[C@@H...,Active
9,122189731.0,CCCCCCCCCCCCCCCCCCCC(=O)N[C@@H](CCC(=O)NCCOCCO...,Active
...,...,...,...
32,20821272.0,COC(=O)C1=C(N=C2C=C(C(=CC2=C1)Cl)Cl)S(=O)(=O)C,Inactive
33,22341151.0,C1CC2=NC3=CC(=C(C=C3N=C2S(=O)(=O)C1)Cl)Cl,Inactive
1,44290899.0,CC[C@H](C)[C@@H](C(=O)N[C@@H](C)C(=O)N[C@@H](C...,Active
2,16007289.0,CC(C)(C)NC1=NC2=CC(=C(C=C2N=C1S(=O)(=O)C)Cl)Cl,Active
3,44449632.0,CC1=CN=C(S1)SC2=NC3=CC(=C(C=C3N=C2C(F)(F)F)Cl)Cl,Active

In [ ]:
msc = pd.read_csv('/Manuscrip_preparation/compounds/miscelan.csv')
msc

         cid                  cmpdname Activity
0  155289405                    WB4-24   Active
1   44393977  [125I]GLP-1-(7-36)-amide   Active
2   90472060              lixisenatide   Active
3   56927919                 exendin-4   Active
4  156588324               tirzepatide   Active
5  134611040               danuglipron   Active
6   56843331               semaglutide   Active
7   16134956               liraglutide   Active
8  145994868               albiglutide   Active

In [ ]:
msci = pd.concat([msc['cid'], msc['cmpdname']], axis =1)
data_3 = msci

Install PubChem python library to compute SMILES from PubChem servers

In [ ]:
!pip install pubchempy  #padelpy to calculate smiles from compound structure if SMILE are unavailable
import pubchempy as pcp   #import pubchempy library
import time as tm

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pubchempy
  Downloading PubChemPy-1.0.4.tar.gz (29 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pubchempy
  Building wheel for pubchempy (setup.py) ... done
  Created wheel for pubchempy: filename=PubChemPy-1.0.4-py3-none-any.whl size=13837 sha256=b77be4157e653deb0c2cafc0bdd37097837ea93a451561b79bc37347c0fb9c9d
  Stored in directory: /root/.cache/pip/wheels/84/45/0e/b597debba098119b642eaf728ae1883d23ad8ea2a9366f2ded
Successfully built pubchempy
Installing collected packages: pubchempy
Successfully installed pubchempy-1.0.4

Compute SMILES from PubChem CID

In [ ]:
data_4 = data_3.dropna(subset=['cid'])
data_4['cid'].dtypes

data_4['cid'] = data_4['cid'].apply(np.int64)

data_4['cid'].dtypes #convert to integer

dtype('int64')

In [ ]:
pubchem_cid = data_4['cid']
print(str(len(pubchem_cid)))

9

In [ ]:
data_4

         cid                  cmpdname
0  155289405                    WB4-24
1   44393977  [125I]GLP-1-(7-36)-amide
2   90472060              lixisenatide
3   56927919                 exendin-4
4  156588324               tirzepatide
5  134611040               danuglipron
6   56843331               semaglutide
7   16134956               liraglutide
8  145994868               albiglutide

In [ ]:
Smiles_1 = []      #create an empty list to store SMILES
for a in pubchem_cid:
    result_1 = pcp.Compound.from_cid(a).isomeric_smiles  #compute SMILES
    Smiles_1.append(result_1)
    tm.sleep(0.1)  #provide delay

In [ ]:
Smiles_1 #list of smiles computed

['CSC1=CC=CC=C1C(=O)NCCCC[C@@H](C2=NC=C(N2)C3=CC4=CC=CC=C4C=C3)NC(=O)C5=CN=CS5',
 'CC[C@H](C)[C@@H](C(=O)N[C@@H](C)C(=O)N[C@@H](CC1=CNC2=CC=CC=C21)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](C(C)C)C(=O)N[C@@H](CCCCN)C(=O)NCC(=O)N[C@@H](CCCN=C(N)N)C(=O)N)NC(=O)[C@H](CC3=CC=CC=C3)NC(=O)[C@H](CCC(=O)O)NC(=O)[C@H](CCCCN)NC(=O)[C@H](C)NC(=O)[C@H](C)NC(=O)[C@H](CCC(=O)N)NC(=O)CNC(=O)[C@H](CCC(=O)O)NC(=O)[C@H](CC(C)C)NC(=O)[C@H](CC4=CC=C(C=C4)O)NC(=O)[C@H](CO)NC(=O)[C@H](CO)NC(=O)[C@H](C(C)C)NC(=O)[C@H](CC(=O)O)NC(=O)[C@H](CO)NC(=O)[C@H]([C@@H](C)O)NC(=O)[C@H](CC5=CC=CC=C5)NC(=O)[C@H]([C@@H](C)O)NC(=O)CNC(=O)[C@H](CCC(=O)O)NC(=O)[C@H](C)NC(=O)[C@H](CC6=CNC=N6)N',
 'CC[C@H](C)[C@@H](C(=O)N[C@@H](CCC(=O)O)C(=O)N[C@@H](CC1=CNC2=CC=CC=C21)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CC(=O)N)C(=O)NCC(=O)NCC(=O)N3CCC[C@H]3C(=O)N[C@@H](CO)C(=O)N[C@@H](CO)C(=O)NCC(=O)N[C@@H](C)C(=O)N4CCC[C@H]4C(=O)N5CCC[C@H]5C(=O)N[C@@H](CO)C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CCCCN)C(=O)N)NC(=O)[C@H](CC6=CC=CC=C6)NC(=O)[C@H](CC(C)C)NC(=O)[C@H](CCCNC(=N)N)NC(=O)[C@H](C(C)C)NC(=O)[C@H](C)NC(=O)[C@H](CCC(=O)O)NC(=O)[C@H](CCC(=O)O)NC(=O)[C@H](CCC(=O)O)NC(=O)[C@H](CCSC)NC(=O)[C@H](CCC(=O)N)NC(=O)[C@H](CCCCN)NC(=O)[C@H](CO)NC(=O)[C@H](CC(C)C)NC(=O)[C@H](CC(=O)O)NC(=O)[C@H](CO)NC(=O)[C@H]([C@@H](C)O)NC(=O)[C@H](CC7=CC=CC=C7)NC(=O)[C@H]([C@@H](C)O)NC(=O)CNC(=O)[C@H](CCC(=O)O)NC(=O)CNC(=O)[C@H](CC8=CNC=N8)N',
 'CCC(C)[C@@H](C(=O)N[C@@H](CCC(=O)O)C(=O)N[C@@H](CC1=CNC2=CC=CC=C21)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](CC(=O)N)C(=O)NCC(=O)NCC(=O)N3CCC[C@H]3C(=O)N[C@@H](CO)C(=O)N[C@@H](CO)C(=O)NCC(=O)N[C@@H](C)C(=O)N4CCC[C@H]4C(=O)N5CCC[C@H]5C(=O)N6CCC[C@H]6C(=O)N[C@@H](CO)C(=O)N)NC(=O)[C@H](CC7=CC=CC=C7)NC(=O)[C@H](CC(C)C)NC(=O)[C@H](CCCNC(=N)N)NC(=O)[C@H](C(C)C)NC(=O)[C@H](C)NC(=O)[C@H](CCC(=O)O)NC(=O)[C@H](CCC(=O)O)NC(=O)[C@H](CCC(=O)O)NC(=O)[C@H](CCSC)NC(=O)[C@H](CCC(=O)N)NC(=O)[C@H](CCCCN)NC(=O)[C@H](CO)NC(=O)[C@H](CC(C)C)NC(=O)[C@H](CC(=O)O)NC(=O)[C@H](CO)NC(=O)[C@H](C(C)O)NC(=O)[C@H](CC8=CC=CC=C8)NC(=O)[C@H](C(C)O)NC(=O)CNC(=O)[C@H](CCC(=O)O)NC(=O)CNC(=O)[C@H](CC9=CNC=N9)N',
 'CC[C@H](C)[C@@H](C(=O)N[C@@H](C)C(=O)N[C@@H](CCC(=O)N)C(=O)N[C@@H](CCCCN)C(=O)N[C@@H](C)C(=O)N[C@@H](CC1=CC=CC=C1)C(=O)N[C@@H](C(C)C)C(=O)N[C@@H](CCC(=O)N)C(=O)N[C@@H](CC2=CNC3=CC=CC=C32)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H]([C@@H](C)CC)C(=O)N[C@@H](C)C(=O)NCC(=O)NCC(=O)N4CCC[C@H]4C(=O)N[C@@H](CO)C(=O)N[C@@H](CO)C(=O)NCC(=O)N[C@@H](C)C(=O)N5CCC[C@H]5C(=O)N6CCC[C@H]6C(=O)N7CCC[C@H]7C(=O)N[C@@H](CO)C(=O)N)NC(=O)[C@H](CCCCNC(=O)CCCCCCCCCCCCCCCCCCC(=O)N[C@@H](CCC(=O)NCCOCCOCC(=O)NCCOCCOCC(=O)O)C(=O)O)NC(=O)[C@H](CC(=O)O)NC(=O)[C@H](CC(C)C)NC(=O)C(C)(C)NC(=O)[C@H]([C@@H](C)CC)NC(=O)[C@H](CO)NC(=O)[C@H](CC8=CC=C(C=C8)O)NC(=O)[C@H](CC(=O)O)NC(=O)[C@H](CO)NC(=O)[C@H]([C@@H](C)O)NC(=O)[C@H](CC9=CC=CC=C9)NC(=O)[C@H]([C@@H](C)O)NC(=O)CNC(=O)[C@H](CCC(=O)O)NC(=O)C(C)(C)NC(=O)[C@H](CC1=CC=C(C=C1)O)N',
 'C1CO[C@@H]1CN2C3=C(C=CC(=C3)C(=O)O)N=C2CN4CCC(CC4)C5=NC(=CC=C5)OCC6=C(C=C(C=C6)C#N)F',
 'CC[C@H](C)[C@@H](C(=O)N[C@@H](C)C(=O)N[C@@H](CC1=CNC2=CC=CC=C21)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](C(C)C)C(=O)N[C@@H](CCCNC(=N)N)C(=O)NCC(=O)N[C@@H](CCCNC(=N)N)C(=O)NCC(=O)O)NC(=O)[C@H](CC3=CC=CC=C3)NC(=O)[C@H](CCC(=O)O)NC(=O)[C@H](CCCCNC(=O)COCCOCCNC(=O)COCCOCCNC(=O)CC[C@H](C(=O)O)NC(=O)CCCCCCCCCCCCCCCCC(=O)O)NC(=O)[C@H](C)NC(=O)[C@H](C)NC(=O)[C@H](CCC(=O)N)NC(=O)CNC(=O)[C@H](CCC(=O)O)NC(=O)[C@H](CC(C)C)NC(=O)[C@H](CC4=CC=C(C=C4)O)NC(=O)[C@H](CO)NC(=O)[C@H](CO)NC(=O)[C@H](C(C)C)NC(=O)[C@H](CC(=O)O)NC(=O)[C@H](CO)NC(=O)[C@H]([C@@H](C)O)NC(=O)[C@H](CC5=CC=CC=C5)NC(=O)[C@H]([C@@H](C)O)NC(=O)CNC(=O)[C@H](CCC(=O)O)NC(=O)C(C)(C)NC(=O)[C@H](CC6=CN=CN6)N',
 'CCCCCCCCCCCCCCCC(=O)N[C@@H](CCC(=O)NCCCC[C@@H](C(=O)N[C@@H](CCC(=O)O)C(=O)N[C@@H](CC1=CC=CC=C1)C(=O)N[C@@H]([C@@H](C)CC)C(=O)N[C@@H](C)C(=O)N[C@@H](CC2=CNC3=CC=CC=C32)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](C(C)C)C(=O)N[C@@H](CCCNC(=N)N)C(=O)NCC(=O)N[C@@H](CCCNC(=N)N)C(=O)NCC(=O)O)NC(=O)[C@H](C)NC(=O)[C@H](C)NC(=O)[C@H](CCC(=O)N)NC(=O)CNC(=O)[C@H](CCC(=O)O)NC(=O)[C@H](CC(C)C)NC(=O)[C@H](CC4=CC=C(C=C4)O)NC(=O)[C@H](CO)NC(=O)[C@H](CO)NC(=O)[C@H](C(C)C)NC(=O)[C@H](CC(=O)O)NC(=O)[C@H](CO)NC(=O)[C@H]([C@@H](C)O)NC(=O)[C@H](CC5=CC=CC=C5)NC(=O)[C@H]([C@@H](C)O)NC(=O)CNC(=O)[C@H](CCC(=O)O)NC(=O)[C@H](C)NC(=O)[C@H](CC6=CN=CN6)N)C(=O)O',
 'CC[C@@H](C)[C@@H](C(=O)N[C@H](C)C(=O)N[C@@H](CC1=CNC2=CC=CC=C21)C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](C(C)C)C(=O)N[C@@H](CCCCN)C(=O)NCC(=O)N[C@@H](CCCNC(=N)N)C(=O)N)NC(=O)[C@H](CC3=CC=CC=C3)NC(=O)[C@H](CCC(=O)O)NC(=O)[C@H](CCCCN)NC(=O)[C@@H](C)NC(=O)[C@@H](C)NC(=O)[C@H](CCC(=O)N)NC(=O)CNC(=O)[C@H](CCC(=O)O)NC(=O)[C@H](CC(C)C)NC(=O)[C@H](CC4=CC=C(C=C4)O)NC(=O)[C@H](CO)NC(=O)[C@H](CO)NC(=O)[C@H](C(C)C)NC(=O)[C@H](CC(=O)O)NC(=O)[C@H](CO)NC(=O)[C@H]([C@H](C)O)NC(=O)[C@H](CC5=CC=CC=C5)NC(=O)[C@H]([C@H](C)O)NC(=O)CNC(=O)[C@H](CCC(=O)O)NC(=O)CNC(=O)[C@H](CC6=CN=CN6)N']

Add SMILES to original file

In [ ]:
data_4.insert(1, 'Smiles', Smiles_1)

data_4['activity'] = 'Active'
data_4 = data_4.drop('cmpdname', axis=1)
validation = data_4.rename({'cid':'PUBCHEM_CID', 'Smiles':'PUBCHEM_EXT_DATASOURCE_SMILES', 'activity':'PUBCHEM_ACTIVITY_OUTCOME'}, axis=1)

In [ ]:
validation.to_csv('/Manuscrip_preparation/compounds/validation.csv')

In [ ]:
#merge data_2 and df_1
dataset = data_2

In [ ]:
dataset['PUBCHEM_ACTIVITY_OUTCOME'].value_counts()

Inactive        374822
Inconclusive      2992
Active             350
Unspecified          5
Name: PUBCHEM_ACTIVITY_OUTCOME, dtype: int64

In [ ]:
dataset.drop_duplicates(subset ="PUBCHEM_CID", inplace = True) # remove all duplicates from data

In [ ]:
dataset['PUBCHEM_ACTIVITY_OUTCOME'].value_counts()

Inactive        371305
Inconclusive      2839
Active             168
Unspecified          5
Name: PUBCHEM_ACTIVITY_OUTCOME, dtype: int64

In [ ]:
dataset = dataset.dropna(subset=['PUBCHEM_CID'])  #remove all NAN values from PUBCHEM_CID

In [ ]:
#SAVE DATA TO CSV
dataset.to_csv('Manuscrip_preparation/compounds/bioactivity_data_glp-1r2.csv')

active = dataset[dataset['PUBCHEM_ACTIVITY_OUTCOME'] == 'Active']
active.to_csv('/Manuscrip_preparation/compounds/active2.csv')

inactive = dataset[dataset['PUBCHEM_ACTIVITY_OUTCOME'] == 'Inactive']
inactive.to_csv('/Manuscrip_preparation/compounds/inactive2.csv')

In [ ]:
inactive_subset = inactive.sample(n=700, random_state = 42)  #randomly select 700 inactives for model training
inactive_subset.to_csv('/Manuscrip_preparation/compounds/inactive_subset2.csv')

In [ ]:
#merge 1000 inactive compounds with available actives
main_data = pd.concat([active, inactive_subset], ignore_index=True, sort=False)
main_data.to_csv('Manuscrip_preparation/compounds/GLP1R_data2.csv')

In [ ]:
main_data

,PUBCHEM_CID,PUBCHEM_EXT_DATASOURCE_SMILES,PUBCHEM_ACTIVITY_OUTCOME
0,44290899.0,CC[C@H](C)[C@@H](C(=O)N[C@@H](C)C(=O)N[C@@H](C...,Active
1,122189729.0,CC[C@H](C)[C@@H](C(=O)N[C@@H](C)C(=O)N[C@@H](C...,Active
2,122189730.0,CCCCCCCCCCCCCCCCCC(=O)N[C@H](CCC(=O)NCCCC[C@@H...,Active
3,122189731.0,CCCCCCCCCCCCCCCCCCCC(=O)N[C@@H](CCC(=O)NCCOCCO...,Active
4,122189732.0,CC[C@H](C)[C@@H](C(=O)N[C@@H](C)C(=O)N[C@@H](C...,Active
...,...,...,...
862,604525.0,CC1=C(C(=NN1CC(=O)NN)C)Br,Inactive
863,2961794.0,CC(C(=O)NC(CC1=CC=C(C=C1)O)C(=O)OC)OC2=CC=CC=C2,Inactive
864,752521.0,CC1(N=C(NC(=N1)NC2=CC(=CC=C2)Br)N)C,Inactive
865,12006165.0,CCSC1=NN=C(C(=O)N1COC(=O)C2=CC=C(C=C2)S(=O)(=O...,Inactive
866,7149776.0,C1CCN(CC1)C2=CC=C(C=C2)NC(=O)COC3=CC4=C(C=C3)C...,Inactive